############################################
##            Made by Asna,Dante          ##
##            1.0-BETA                    ##
##            AsnaCode                    ##
##            Private System              ##
############################################

#Wartungsmodus
Wartungen: false

#MuteChat
MuteChat: false

#Discord

CHANNEL_ID: 1080515591573618710
GUILD_ID: 1076484475187384320
TOKEN: MTA4MDUxMzcwMjU3NjUyNTQwNA.GruZf_.EcWgGKnSa83Vf9XdxyXmfSc-iu1YLJ0cmuRNQc
CHANNEL_TEAM_ID: 1080569593787072643

BUG_REPORT_ID: 1081247732817219624
REPORT_ID: 1081271041730551931