name: AsnaBuild
version: '${project.version}'
main: at.asna.asnabuild.Main
api-version: 1.19
authors: [ Asna ]
description: private system
website: https://asnacode.de/
commands:
  setspawn:
  spawn:
    aliases: [l, lobby, hub]
  wartungen:
  gamemode:
    aliases: [gm]
  fly:
    aliases: [fliegen]
  clearchat:
    aliases: [cc]
  teleport:
    aliases: [tp]
  teleporthere:
    aliases: [tph, tphere]
  heal:
  food:
    aliases: [feed]
  invsee:
  skull:
    aliases: [kopf, head]
  giveaway:
  hilfe:
  setwarp:
  warps:
    aliases: [warp]
  money:
  addmoney:
  removemoney:
  daily:
  enderchest:
    aliases: [ec]
  broadcast:
    aliases: [bc, rundruf]
  social:
    aliases: [discord, youtube, dc, yt, twitch, tw, sozial, updates]
  msg:
    aliases: [r]
  sethome:
  home:
  homes:
  delhome:
  pay:
    aliases: [überweisen]
  craft:
    aliases: [workbench, crafting]
  anvil:
  day:
    aliases: [tag]
  night:
    aliases: [nacht]
  shop:
  vanish:
    aliases: [v]
  kick:
  ban:
  unban:
  rang:
    aliases: [rank, upgraderank, upgraderang]
  setmoney:
  job:
  uuid:
  tempban:
  mutechat:
  sign:
  rename:
  ip:
    aliases: [adress, ip-adress]
  tpa:
    aliases: [tpaaccept]
  sun:
    aliases: [sonne]
  rain:
    aliases: [regen]
  entchant:
    aliases: [verzaubern]
  repair:
  verkaufen:
    aliases: [sell]
  ping:
    aliases: [ms]
  pchatclear:
    aliases: [pcc]
  nick:
  bug:
  report:
    aliases: [melden, hacker]
